s1 = "RATPTRWPVGCFNRPWTKWSYDEALDGIKAAGYAWTGLLTASKPSLHHATATPEYLAALKQKSRHAA"
s2 = "AAAVMMGLAAIGAAIGIGILGGKFLEGAARQPDLIPLLRTQFFIVMGLVDAIPMIAVGLGLYVMFAVA"
s3 = "AADVSAAVGATGQSGMTYRLGLSWDWDKSWWQTSTGRLTGYWDAGYTYWEGGDEGAGKHSLSFAPVFVYEFAGDSIKPFIEAGIGVAAFSGTRVGDQNLGSSLNFEDRIGAGLKFANGQSVGVRAIHYSNAGLKQPNDGIESYSLFYKIPI"




aa = "ACDEFGHIKLMNPQRSTVWY"

for x in [("seq1", s1), ("seq2", s2), ("seq3", s3)]:
    print(x[0])
    l = len(x[1])
    for a in aa:
        c = x[1].count(a)
        p = (c / l) * 100
        print(a, round(p, 2))